ecomapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name="ecomapp"
urlpatterns = [
    path("",HomeView.as_view(),name="home"),
    path("about/", AboutView.as_view(),name="about"),
    path("contact-us/",ContactView.as_view(),name="contact"),
    path("all-products/",AllProductView.as_view(),name="allproducts"),
    path("product/<slug:slug>/",ProductDetailView.as_view(),name="productdetail"),

    path("add-to-cart-<int:pro_id>/",AddToCartView.as_view(),name="addtocart"),
    path("my-cart/",MyCartView.as_view(),name="mycart"),
    path("manage-cart/<int:cp_id>/",ManageCartView.as_view(),name="managecart"),
    path("empty-cart/",EmptyCartView.as_view(),name="emptycart"),

    path("checkout/",CheckoutView.as_view(),name="checkout"),
    path("register/",CustomerRegistrationView.as_view(),name="customerregistration"),
    path("logout/",CustomerLogoutView.as_view(),name="customerlogout"),
    path("login/",CustomerLoginView.as_view(),name="customerlogin"),
    path("profile", CustomerProfileView.as_view(),name="customerprofile"),
    path("profile/order-<int:pk>/",CustomerOrderDetailView.as_view(),name="customerorderdetail"),

    path("admin-login/",AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/",AdminHomeView.as_view(),name="adminhome"),
    path("admin-order/<int:pk>/",AdminOrderDetailView.as_view(),name="adminorderdetail"),
    path("admin-all-orders/",AdminOrderListView.as_view(),name="adminorderlist"),
    path("admin-order-<int:pk>-change/",AdminOrderStatusChangeView.as_view(),name="adminorderstatuschange")




]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("ecomapp.urls")),
]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Admin(models.Model):
    user= models. OneToOneField(User, on_delete=models.CASCADE)
    full_name= models.CharField(max_length=50)
    image=models.ImageField(upload_to="admins")
    mobile=models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

class Customer(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    full_name=models.CharField(max_length=200)
    address=models.CharField(max_length=200, null=True, blank=True)
    joined_on=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

class Category(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    image=models.ImageField(upload_to="products")
    marked_price=models.PositiveIntegerField()
    selling_price=models.PositiveIntegerField()
    description=models.TextField()
    warranty=models.CharField(max_length=300,null=True,blank=True)
    return_policy=models.CharField(max_length=300,null=True,blank=True)
    view_count=models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

class Cart(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL, null=True, blank=True)
    total=models.PositiveIntegerField(default=0)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)



class CartProduct(models.Model):
    cart=models.ForeignKey(Cart, on_delete=models.CASCADE)
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    rate=models.PositiveIntegerField()
    quantity=models.PositiveIntegerField()
    subtotal=models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + "CartProduct: " +str(self.id)



ORDER_STATUS=(
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way","On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Cancelled", "Order Cancelled"),



)



class Order(models.Model):
    cart=models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by=models.CharField(max_length=200)
    shipping_address=models.CharField(max_length=200)
    mobile=models.CharField(max_length=10)
    email=models.EmailField(null=True, blank=True)
    subtotal=models.PositiveIntegerField()
    discount=models.PositiveIntegerField()
    total=models.PositiveIntegerField()
    order_status=models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order: "  + str(self.id)

templates/about.html
{% extends 'base.html' %}
{% block title %}About Us{% endblock %}
{% block content %}

    <h1>we are the emerging ecommerce in the city.</h1>
{% endblock %}

templates/addtocart.html
{% extends 'base.html' %}

{% block title %} Add to cart {% endblock %}

{% block content %}
<div class="container">
    <h3>product added to cart successfully.</h3>
</div>
{% endblock %}

templates/allproducts.html
{% extends 'base.html' %}
{% block title %} All Products {% endblock %}
{% block content %}


<div class="container">
    <h3>All Products</h3><hr>
    {% for cat in allcategories %}

    <h4>{{cat.title}}</h4>
    <div class="row">
        {% for p in cat.product_set.all %}
        <div class="col-md-4">
            <div class="m-4">
                <h4><a href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h4>
                <img src="{{p.image.url}}" alt="" width=200; class="img.fluid" style="height:2500; object-fit; cover;">
                <p class="mt-3">Price:<strike>Rs.{{p.marked_price}}</strike>Rs. {{p.selling_price}}</p>
                <a href="{% url 'ecomapp:addtocart' p.id%}" class="btn btn-primary">Add Tip Cart</a>
            </div>

        </div>
        {% endfor %}
    </div>

    {% endfor %}

</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title><!-- CSS only -->
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<body>
    <div class="container">


        <a href="{% url 'ecomapp:home' %}">Home</a>
        <a href="{% url 'ecomapp:about' %}">About Us</a>
        <a href="{% url 'ecomapp:contact' %}">contact us</a>
        <a href="{% url 'ecomapp:allproducts' %}">Categories</a>
        <a href="{% url 'ecomapp:mycart' %}">View Cart</a>

        {% if request.user.customer %}
        Welcome {{request.user.username }}!
        <a href="{% url 'ecomapp:customerprofile' %}">My profile</a>
        <a href="{% url 'ecomapp:customerlogout' %}">Logout</a>
        {% else %}
        <a href="{% url 'ecomapp:customerregistration' %}">Register</a>
        <a href="{% url 'ecomapp:customerlogin' %}">Login</a>
        {% endif %}

    </div>
    <hr>

    {% block content %}

    {% endblock %}


</body>
</html>

templates/checkout.html
{% extends 'base.html' %}

{% block title %} Checkout {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Items in the  cart</h3>
            <a href="{% url 'ecomapp:mycart' %}">Update Cart</a>

            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right" >Total</th>
                        <th>Rs.{{cart.total}}</th>
                    </tr>
                </tbody>
            </table>


        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-info">Place Order</button>

            </form>
        </div>

    </div>
</div>


{% endblock %}

templates/contactus.html
{% extends 'base.html' %}
{% block title %}Contact Us{% endblock %}
{% block content %}
<h1>To Contact us, Call the following numbers</h1>
<p>7907397914</p>
<p>1234567890</p>

{% endblock %}

templates/customerlogin.html
{% extends 'base.html' %}
{% block title %} Customer Login {% endblock %}


{% block content %}

<style>
    .errorlist{
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Login Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">login as Customer</button>
                {% if error %}
                <li style="color:red;">{{error}}</li>
                {% endif %}


            </form>
            <p>or don't have account?</p><a href="{% url 'ecomapp:customerregistration' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register here</a>
        </div>
    </div>
</div>

{% endblock %}

templates/customerorderdetail.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}Order Detail {% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Detail</h3><hr>
            <p><span class="font-weight-bold">Order ID:</span> #ORDER_{{ord_obj.id}}</p>
            <p><span class="font-weight-bold">Order Status:</span>{{ord_obj.order_status}}</p>
            <p><span class="font-weight-bold">Order On:</span>{{ord_obj.created_at}} ({{ord_obj.created_at|timesince}}ago)</p>
            <p><span class="font-weight-bold">Customer Information:</span>By {{ord_obj.ordered_by}},{{ord_obj.mobile}}</p>
            <p><span class="font-weight-bold">Shipping Address:</span> By {{ord_obj.shipping_address}} ({{ord_obj.email}})</p>
            <h4>Ordered Items</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>

                    </tr>
                </thead>
                <tbody>
                    {% for cp in  ord_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a target="_blank" href="{% url 'ecomapp:productdetail' cp.product.slug %}">{{cp.product.title}} ({{cp.product.id}})</a></td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>

                    </tr>

                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total:</th>
                        <th>Rs{{ord_obj.total}}/-</th>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/customerprofile.html
{% extends 'base.html' %}


{% block title %}My Profile {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Detail Information</h3><hr>
            <p><span class="font-weight-bold">Name:</span>{{customer.full_name}}</p>
            <p><span class="font-weight-bold">Username:</span>{{customer.user.username}}</p>
            <p><span class="font-weight-bold">Email:</span>{{customer.user.email}}</p>
            <p><span class="font-weight-bold">Address:</span>{{customer.address}}</p>
            <p><span class="font-weight-bold">Joined on:</span>{{customer.joined_on}}</p>
        </div>
        <div class="col-md-8">
            <h3>Previous Orders</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID</th>
                        <th>Amount</th>
                        <th>Ordered</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ord in orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecomapp:customerorderdetail' ord.pk %}">#ORDER_{{ord.id}}</a></td>
                        <td>{{ord.total}}</td>
                        <td>{{ord.created_at|timesince}} ago</td>
                        <td>{{ord.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

templates/customerregistration.html
{% extends 'base.html' %}
{% block title %} Customer Registration {% endblock %}


{% block content %}

<style>
    .errorlist{
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Registration Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Register as Customer</button>

            </form>
            <p>Already have an account?</p><a href="{% url 'ecomapp:customerlogin' %}">Login here</a>

        </div>
    </div>
</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}

<div class="container">


    <h1 class="text-center">welcome to ecommerce website.</h1>
    <div class="row mt-3">
        {% for p in product_list %}
        <div class="col-md-4">
            <h4><a href="{% url 'ecomapp:productdetail' p.slug %}"></a>{{p.title}}</h4>
            <img src="{{p.image.url}}" alt="" width=200; class="img.fluid" style="height:2500; object-fit; cover;">
            <p class="mt-3">Price:<strike>Rs.{{p.marked_price}}</strike>Rs. {{p.selling_price}}</p>
            <a href="{% url 'ecomapp:addtocart' p.id%}" class="btn btn-primary">Add Tip Cart</a>


        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/mycart.html
{% extends 'base.html' %}

{% block title %} My Cart {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items in my cart</h4><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>

                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=decr" class="btn btn-warning"> - </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=remv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>

                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs.{{cart.total}}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="{% url 'ecomapp:emptycart' %}">Empty Cart</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a class="btn btn-info" href="{% url 'ecomapp:checkout' %}">Checkout</a></th>
                    </tr>
                    {% endif %}

                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

templates/productdetail.html
{%extends 'base.html'%}
{% block title %}{{product.title}}{% endblock %}

{% block content %}
<div class="container">

    <h3>Product: {{product.title}}</h3><hr>
    <div class="row">
        <div class="col-md-6">
            <img src="{{product.image.url}}" alt="" class="img.fluid">

        </div>
        <div class="col-md-6">
            <h4>{{product.title}} (Viewd {{product.view_count}} times)</h4>
            <h5>Category: {{product.category}}</h5>
            <h5>Price:<strike>Rs. {{product.marked_price}}</strike>Rs.{{product.selling_price}}</h5>
            <a href="{% url 'ecomapp:addtocart' product.id%}" class="btn btn-info">Add To Cart</a>
            <hr>
            <p class="text-info">warrenty:{{product.warrenty}}</p>
            <p class="text-info">Return Policy:{{product.return_policy}}</p>
            <hr>
            <p>{{product.description}}</p>
        </div>
    </div>
</div>
{% endblock %}